// Exact runtime cache names generated by the retired next-pwa configuration.
export const RETIRED_WEB_CACHES = [
  'start-url', 'google-fonts-webfonts', 'google-fonts-stylesheets',
  'static-font-assets', 'static-image-assets', 'next-static-js-assets', 'next-image',
  'static-audio-assets', 'static-video-assets', 'static-js-assets', 'static-style-assets',
  'next-data', 'static-data-assets', 'apis', 'pages-rsc-prefetch', 'pages-rsc', 'pages', 'cross-origin',
]
export const isRetiredWebCache = (name: string) => RETIRED_WEB_CACHES.includes(name) || /^(?:workbox-|next-pwa)/.test(name)
