import type { LegalCopy, LegalDocumentKind } from '@/app/[locale]/_legal/legalContent'
import type { PublicLocale } from '@/lib/i18n/routing'
export function platformLegalCopy(locale: PublicLocale, document: LegalDocumentKind, content: LegalCopy): LegalCopy {
  if (document !== 'privacy') return content
  const en = locale === 'en'
  const copy = (es: string, english: string) => en ? english : es
  return {
    ...content,
    lastUpdated: copy('16 de septiembre de 2026', 'September 16, 2026'),
    intro: copy('Esta política describe Vekira para Android, que guarda tu entrenamiento en el dispositivo. Las funciones conectadas y la web utilizan los datos que necesitan para prestar el servicio que eliges.', 'This policy describes Vekira for Android, which stores your training on your device. Connected features and the website use the data needed to provide the service you choose.'),
    sections: [
      { title: copy('1. Datos en este dispositivo', '1. Data on this device'), paragraphs: [copy('El perfil, rutinas, sesiones, medidas, objetivos y borradores se guardan en el almacenamiento privado de la app para funcionar sin conexión. Pueden incluir datos sensibles, como peso, lesiones o limitaciones que decidas registrar. Cerrar sesión conserva los perfiles locales; desinstalar o borrar los datos de Android puede eliminarlos.', 'Your profile, plans, sessions, measurements, goals and drafts are saved in private app storage for offline use. They may include sensitive information such as weight, injuries or limitations you choose to record. Signing out preserves local profiles; uninstalling or clearing Android app data can remove them.')] },
      { title: copy('2. Cuenta, conexión y respaldo', '2. Account, connection and backup'), paragraphs: [copy('Supabase gestiona el acceso de la cuenta y los datos conectados. Al iniciar sesión se descargan los datos necesarios a este dispositivo. Puedes sincronizar el respaldo móvil desde Ajustes; las funciones que eliges conectar, como el compañero de constancia y Fitness Card, también pueden sincronizar cambios automáticamente con tu cuenta. El respaldo contiene registros personales y de entrenamiento. Un perfil usado solo sin conexión no publica por sí mismo esos registros.', 'Supabase handles account access and connected data. Signing in downloads necessary records to this device. You can sync the mobile backup from Settings; features you choose to connect, such as the consistency companion and Fitness Card, may also sync changes automatically with your account. Backups contain personal and training records. A profile used only offline does not publish those records by itself.')] },
      { title: copy('3. Planificación y chat', '3. Planning and chat'), paragraphs: [copy('La planificación personal de esta versión Android usa reglas locales: no envía tu perfil a Anthropic para generar una rutina. El chat con el coach se abre, por decisión tuya, en la web de Vekira y requiere acceso independiente. Esta app no genera ni guarda conversaciones simuladas. Si utilizas funciones de IA en la web, se aplica la información sobre proveedores y tratamiento de datos de esa web.', 'Personal planning in this Android version uses local rules: it does not send your profile to Anthropic to generate a plan. Coach chat opens on the Vekira website when you choose, with a separate sign-in. This app does not generate or save simulated conversations. If you use AI features on the website, that website explains its providers and data processing.')] },
      { title: copy('4. Exportar y restaurar', '4. Export and restore'), paragraphs: [copy('Los archivos de respaldo que exportas contienen información personal y de entrenamiento sin cifrar; no incluyen la contraseña ni el token de acceso. Al compartirlos, la aplicación o persona destinataria recibe ese archivo. Guárdalos en un lugar privado. La restauración puede reemplazar datos de esa misma cuenta tras tu confirmación y conserva una copia previa en el dispositivo para recuperarla.', 'Exported backup files contain unencrypted personal and training information; they do not include your password or access token. Sharing a backup gives the file to the recipient or chosen app. Keep it private. Restore may replace the same account’s data after confirmation and preserves a prior copy on the device for recovery.')] },
      { title: copy('5. Música y acceso a notificaciones', '5. Music and notification access'), paragraphs: [copy('La integración de música es opcional. El permiso de acceso a notificaciones de Android permite consultar las sesiones multimedia activas para mostrar título, artista, aplicación, carátula y estado de reproducción, y enviar controles al reproductor. Esa información se procesa en el dispositivo; esta integración no sube el contenido de tus notificaciones ni las canciones a Vekira. Puedes revocar el acceso en Ajustes de Android.', 'Music integration is optional. Android notification access lets the app query active media sessions to display title, artist, app, artwork and playback state, and send controls to the player. This information is processed on the device; this integration does not upload notification contents or songs to Vekira. You can revoke access in Android Settings.')] },
      { title: copy('6. Recordatorios y servicios conectados', '6. Reminders and connected services'), paragraphs: [copy('Los recordatorios locales se programan en este dispositivo para la cuenta que los activa. Las notificaciones remotas, cuando están disponibles y las habilitas, usan un identificador técnico y un token del dispositivo para su entrega. Las funciones profesionales, las tarjetas públicas y los archivos que subes envían al servidor los datos necesarios y respetan los permisos de la cuenta. Los trámites web se abren solo al pulsar el enlace; no transferimos tu token de Android en la dirección web.', 'Local reminders are scheduled on this device for the account that enables them. Remote notifications, when available and enabled, use a technical identifier and device token for delivery. Professional features, public cards and uploaded files send necessary data to the server under account permissions. Web tasks open only when you press the link; your Android token is not transferred in the web address.')] },
      { title: copy('7. Conservación y control de tus datos', '7. Retention and control of your data'), paragraphs: [copy('Puedes consultar, corregir y exportar tus registros desde Vekira y solicitar la eliminación de tu cuenta en Ajustes o en la web. La app elimina la copia local de esa cuenta cuando el servidor confirma su eliminación; las copias exportadas y otros dispositivos requieren su propia limpieza. Para solicitudes de acceso, portabilidad o supresión, usa el contacto indicado abajo.', 'You can review, correct and export your records in Vekira and request account deletion in Settings or on the website. The app removes that account’s local copy when the server confirms deletion; exported files and other devices require their own cleanup. Contact us below for access, portability or erasure requests.'), copy('Si eres entrenador, las rutinas ya entregadas a tus clientes y su historial permanecen en las cuentas de esos clientes; las rutinas quedan archivadas y sin relación profesional activa. Se conservan registros de auditoría profesional con identificadores de cuenta y datos de la actividad registrada.', 'If you are a trainer, plans already delivered to your clients and their history remain in those clients’ accounts; the plans are archived without an active professional relationship. Professional audit records retain account identifiers and recorded activity data.')] },
      { title: copy('8. Proveedores y seguridad', '8. Providers and security'), paragraphs: [copy('Supabase presta autenticación, base de datos y almacenamiento de archivos conectados; Vercel aloja la web y servicios asociados. Las conexiones usan HTTPS y los datos remotos tienen controles de acceso. El almacenamiento local depende de la protección del dispositivo: protege el bloqueo de pantalla y los archivos exportados. Ningún sistema ofrece seguridad absoluta.', 'Supabase provides authentication, database and connected file storage; Vercel hosts the website and associated services. Connections use HTTPS and remote data has access controls. Local storage depends on device protection: protect your screen lock and exported files. No system provides absolute security.')] },
      content.sections[8], content.sections[9],
    ],
  }
}
