'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

export function NewProgramTemplateForm() {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { const result = await (await import('@/app/actions/trainerPrograms')).createTrainerProgram(new FormData(event.currentTarget)); if (result.ok) router.push(`/coach/programs/${result.templateId}`); else setError(result.error) } catch { setError('No se pudo crear la rutina.') } finally { setSaving(false) } }
  return <form onSubmit={event => void submit(event)} noValidate className="rounded-3xl border border-border/70 bg-muted/10 p-5 sm:p-6"><h1 className="text-xl font-bold text-foreground">Crea una plantilla</h1><p className="mt-1 text-sm text-muted-foreground">Las asignaciones publicadas conservan su propia versión y no cambiarán si editas esta plantilla.</p><div className="mt-6 grid gap-4"><label className="text-sm font-semibold text-foreground">Nombre<input name="name" required maxLength={120} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal" /></label><label className="text-sm font-semibold text-foreground">Objetivo<input name="goal" maxLength={240} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal" /></label><label className="text-sm font-semibold text-foreground">Días por semana<select name="daysPerWeek" defaultValue="3" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal">{[1,2,3,4,5,6,7].map(day => <option key={day} value={day}>{day}</option>)}</select></label><label className="text-sm font-semibold text-foreground">Descripción<textarea name="description" rows={4} maxLength={2000} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-2 font-normal" /></label></div><button type="submit" disabled={saving} className="mt-6 min-h-11 rounded-xl bg-violet-500 px-4 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Creando…' : 'Crear plantilla'}</button>{error ? <p role="alert" className="mt-3 text-sm text-red-300">{error}</p> : null}</form>
}
