import { useState, type FormEvent } from 'react'
import { Download, Upload, Cloud, RefreshCw, UserRound, ShieldCheck } from 'lucide-react'
import { Capacitor } from '@capacitor/core'
import type { MobileAccount, MobileRepository } from '../domain/types'
import type { MobileCloud } from '../cloud/types'
import { shareBackup } from './backup'
import { recoverLegacyDrafts } from '../native/legacyRecovery'

export function Settings({ account, accounts, repository, cloud, online, pending, syncStatus, sync, activate, refresh, editProfile, newProfile, notify, openMeasurements }: { account: MobileAccount; accounts: MobileAccount[]; repository: MobileRepository; cloud: MobileCloud; online: boolean; pending: number; syncStatus: string; sync: () => Promise<void>; activate: (account: MobileAccount) => Promise<void>; refresh: () => Promise<void>; editProfile: () => void; newProfile: () => void; notify: (message: string) => void; openMeasurements: () => void }) {
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [sourceProfile, setSourceProfile] = useState('')
  const [copyConsent, setCopyConsent] = useState(false)
  async function run(action: () => Promise<void>, success?: string) { setBusy(true); setError(''); setMessage(''); try { await action(); if (success) setMessage(success) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo completar la operación.') } finally { setBusy(false) } }
  async function login(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget)
    await run(async () => { const linked = await cloud.signIn(String(form.get('email')), String(form.get('password'))); await activate(linked); notify('Cuenta conectada. Tu perfil local permanece disponible en Ajustes.') })
  }
  return <div className="stack"><div className="section-heading"><span className="eyebrow">A TU MANERA</span><h1>Ajustes</h1><p>Tu perfil, tus datos y tu conexión.</p></div>
    {error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}
    <section className="card stack"><div className="row"><div className="avatar">{account.name.slice(0, 1)}</div><div><h2>{account.name}</h2><span className="muted">{account.remoteUserId ? 'Perfil con cuenta conectada' : 'Perfil local'}</span></div></div><button className="secondary full" onClick={editProfile}><UserRound size={18} />Editar perfil y preparación</button><button className="secondary full" onClick={openMeasurements}>Registrar medidas corporales</button></section>
    <section className="card stack"><div className="row"><Cloud className="violet" /><h2>Cuenta y respaldo móvil</h2></div><div className="row between"><span className="chip">{online ? 'Con conexión' : 'Sin conexión'}</span><span className="muted">{pending} pendientes</span></div><p role="status" className="muted">{syncStatus || (account.remoteUserId ? 'Tus cambios se conservan en este dispositivo.' : 'Puedes usar Vekira sin una cuenta.')}</p><p className="small-text muted">El respaldo móvil conserva tu progreso en la nube. El progreso registrado aquí todavía no se refleja en la web.</p>
      {account.remoteUserId ? <><button className="primary full" disabled={busy || !online || !cloud.configured} onClick={() => void run(sync)}><RefreshCw size={18} />Sincronizar ahora</button><button className="secondary full" disabled={busy} onClick={() => void run(async () => { await cloud.signOut(); await refresh() }, 'Sesión de internet cerrada. El perfil sigue disponible en este dispositivo.')}>Cerrar sesión de internet</button></> : cloud.configured ? <form className="stack" onSubmit={login}><label>Correo electrónico<input name="email" type="email" autoComplete="username" required /></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required /></label><p className="small-text muted">Al conectar se abrirá el perfil de esa cuenta. Tu perfil local se conserva por separado.</p><button className="primary full" disabled={busy || !online}>{busy ? 'Conectando…' : 'Conectar mi cuenta'}</button></form> : <p className="notice">La conexión de cuenta no está configurada en esta versión. Tus datos locales y respaldos siguen disponibles.</p>}
      {account.remoteUserId && cloud.configured && <details className="instructions"><summary>Volver a conectar mi cuenta</summary><form className="stack" onSubmit={login}><label>Correo electrónico<input name="email" type="email" autoComplete="username" required /></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required /></label><button className="primary full" disabled={busy || !online}>Conectar mi cuenta</button></form></details>}
    </section>
    <section className="card stack"><div className="row"><ShieldCheck className="violet" /><h2>Tus datos, contigo</h2></div><p className="muted">Guarda una copia de tus rutinas, sesiones, medidas y perfil. El respaldo no contiene tu contraseña.</p><button className="secondary full" disabled={busy} onClick={() => void run(async () => shareBackup(await repository.exportBackup(account.id)), 'Respaldo preparado')}><Download size={18} />Exportar respaldo</button><label className={`secondary full file-picker ${busy ? 'disabled' : ''}`}><Upload size={18} />Importar respaldo<input type="file" accept=".json,application/json" disabled={busy} aria-label="Importar respaldo" onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; void run(async () => { const restored = await repository.importBackup(await file.text()); await activate(restored); notify('Respaldo importado') }) }} /></label><p className="small-text muted">Se validará el archivo antes de importar. Los datos de otros perfiles permanecen separados.</p>
      {Capacitor.isNativePlatform() && account.remoteUserId && <button className="secondary full" disabled={busy} onClick={() => void run(async () => { const result = await recoverLegacyDrafts(repository, account); await refresh(); setMessage(`${result.recovered} sesiones recuperadas · ${result.skipped} omitidas`) })}>Recuperar sesión de la versión anterior</button>}
    </section>
    {account.remoteUserId && accounts.some(a => !a.remoteUserId && a.id !== account.id) && <section className="card stack"><h2>Incorporar un perfil local</h2><p className="muted">Copia rutinas, sesiones y medidas a esta cuenta para incluirlas en su respaldo móvil. El perfil original se conserva y esta cuenta mantiene sus datos de preparación.</p><label>Perfil de origen<select value={sourceProfile} onChange={e => { setSourceProfile(e.target.value); setCopyConsent(false) }}><option value="">Seleccionar perfil</option>{accounts.filter(a => !a.remoteUserId && a.id !== account.id).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={copyConsent} onChange={e => setCopyConsent(e.target.checked)} />Confirmo que estos registros me pertenecen y quiero copiarlos a {account.name}.</label><button className="secondary full" disabled={busy || !sourceProfile || !copyConsent} onClick={() => void run(async () => { await repository.importBackup(await repository.exportBackup(sourceProfile), account.id); await refresh(); setCopyConsent(false) }, 'Registros incorporados a esta cuenta')}>Copiar registros a mi cuenta</button></section>}
    <section className="card stack"><h2>Perfiles en este dispositivo</h2>{accounts.map(a => <div className="row between" key={a.id}><div><strong>{a.name}</strong><p className="muted small-text">{a.remoteUserId ? 'Cuenta conectada' : 'Local'}{a.id === account.id ? ' · En uso' : ''}</p></div>{a.id !== account.id && <button className="secondary small" disabled={busy} onClick={() => void run(async () => { await cloud.signOut(); await activate(a) })}>Cambiar</button>}</div>)}<button className="secondary full" disabled={busy} onClick={newProfile}>Crear otro perfil local</button></section><p className="footer-note">VEKIRA · Tu entrenamiento, siempre contigo.</p>
  </div>
}
